cors:
  allowed:
    origins: http://localhost:9090
hystrix:
  threadpool:
    default: 
      coreSize: 1000
      maxQueueSize: 100000
      queueSizeRejectionThreshold: 10000
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

logging.level:
  org.springframework.web: ERROR